# Overview over topics from the Estonian A1 course

## Overview of Grammar Forms
| Grammar Form | Estonian Name       | Endings |
|--------------|-------------|-------------|
| 1. Nominative   | Nominatiiv          |
| 2. Genitive     | Omastav/Genitiiv    | 1) nominatiiv + -i, -e, -a, -u, 2) sõna mutub |
| 3. Partitive    | Osastav/Partitiiv   |  1) osastav + -t, -d, -/ 2) sõna mutub |
| 4. Locative - Where?        | Kus?               | 1) osastav + -s, -l 2) sõna mutub |
| 5. Locative - Where to?     | Kuhu?              | 1) osastav + -sse, -le 2) sõna mutub |
| 6. Locative - Where from?   | Kust?              | 1) osastav + -st, -lt 2) sõna mutub |
| 13. Ilmaütlev | Ilmaütlev/Abessiv | omastav + -ta  |
| 14. Kaasaütlev | Kaasaütlev/Comitative | omastav + -ga |

- When to use the different cases?
    - Nominative: subject of the sentence
    - Genitive: possession, origin
        - when combining two nouns, the first noun is in genitive case
            - leivasupp, juustuleib, õunapuu, autojuht, tomatipasta
        - indicating possession
            - Mu venna nimi on..., Mu sõbra auto on..., Mu ema töö on...
    - Partitive: part of a whole, indefinite quantity
        - Ma joon vett, Kaks pakk võid, Ma söön leiba, Ma vaatan telekat, Ma kuulan muusikat, Ma loen raamatut, Ma teen tööd, Ma räägin eesti keelt
        - Ainsus osastav: 
        - at -> aid, it -> eid, i/- -> eid, u -> uid, e -> id
        - Plural of Osastav (e.g. when getting a kilo of something)
            - Palun kilo õunu (special), banaane (special), viinamarju, kartuleid, porgandeid, sibulaid, tomateid
        -  However, one of something, use nominative:
            - Palun üks õun, banaan, viinamarja, kartul, porgand, sibul, tomat
    - Locative:
        - Kus? - in, on, at
            - Formed: omastav + -s, -l
            - Kus sa oled? - Ma olen Eestis? Ma olen kodus, Ma olen tööl, Ma olen poes, Ma olen koolis, ma olen turul 
        - Kuhu? - to, into
            - Formed: omastav + -sse, -le
            - Special endings for some words:
                - E.g. kool -> kooli, pood -> poodi, turg -> turule, töö -> tööle, sauna -> sauna, kodu -> koju, peol -> peole
            - Kuhu sa lähed? - Ma lähen Eestisse, Ma lähen koju, Ma lähen tööle, Ma lähen poodi, Ma lähen kooli, ma lähen turule
        - Kust? - from, out of (tulema = to come)
            - Kust sa tuled? - Ma tulen Eestist, Ma tulen kodust, Ma tulen tööst, Ma tulen poest, Ma tulen koolist, ma tulen turult

    - Kaasaütlev: When something or someone is with something or someone -ga form:
        - Ma jalutan koeraga, ma joon teed suhkruga, ma räägin sõbraga (või sõbradega when plural)
    - Ilmaütlev: When something or someone is without something or someone -ta form:
        - Ma jalutan ilma koerata, ma joon teed ilma suhkruta, ma räägin ilma sõbrata (või sõpradeta when plural)

## Practical Grammar
- How to say hello and goodbye?
    - Tere! (Hello!)
    - Tere hommikust! (Good morning!)
    - Tere päevast! (Good day!)
    - Tere õhtust! (Good evening!)
    - Head aega! (Goodbye!)
    - Nägemist! (See you!)
    - Olge head! (Be well!)
    - Tšau! (Bye!)
- How to ask for time: l. 12
    - Mis kell on?
    - Kui palju kell on?
    - Palju kell on?
    - Mis kell sa lähed tööle?
- Yesterday, today, tomorrow: l. 13
    - Eile
    - Täna
    - Homme
    - Üleeile
    - Ülehomme
- Where are you from? Kust sa pärit oled/olete? Mis on sinu rahvus (nationality)? Kus sa elad/elasid? Mis keelt sa räägid?
    - Ma olen pärit maa+[st,lt]: 
        - Eestist, Soomest, Venemaalt, Saksamaalt, Prantsusmaalt, Inglismaalt, Ameerikast
    - Ma olen maa+[lane]:
        - eestlane, soomlane, venelane, sakslane, prantslane, inglane, ameeriklane
    - Ma elan maa+[s,es]:
        - Eestis, Soomes, Venemaal, Saksamaal, Prantsusmaal, Inglismaal, Ameerikas
    - Ma [räägin/ei räägi, oskan/ei oska]+[keelt]:
        - eesti keelt, soome keelt, vene keelt, saksa keelt, prantsuse keelt, inglise keelt, ameerika keelt
    - E.g. Nadir on parit Eestist, ta on eestlane. Ta elab Eestis ja räägib eesti keelt.
    - Plural: 
        - Me oleme pärit Eestist, Soomest, Venemaalt, Saksamaalt, Prantsusmaalt, Inglismaalt, Ameerikast
        - Me oleme eestlased, sakslased...
        - Me elame Eestis...
        - Me räägime eesti keelt...

- How to say I like something?
    - Mulle meeldib... (I like...)
        - Mulle meeldib see raamat, muusika, film, jook, toit, koht, inimene
        - Meile meeldib see raamat, muusika, film, jook, toit, koht, inimene
        - Mulle ei meeldi see raamat, muusika, film, jook, toit, koht, inimene
- How to say I like to eat something?
    - Mulle maitseb... (I like to eat...)
        - Mulle maitseb see raamat, muusika, film, jook, toit, koht, inimene
        - Mulle maitsevad porgandid, kartulid, tomatid, õunad, banaanid, viinamarjad
        - Mulle ei maitse see raamat, muusika, film, jook, toit, koht, inimene
        - Mulle maitseb juust, ja ma söön juustu
- How often do you do something? Kui tihti sa teed midagi?
    - Ma käin iga päev, iga nädal, iga kuu, iga aasta
    - Ma käin tihti, mõnikord, harva, mitte kunagi
    - Mida sa reedel õhtul teed?
        - Ma käin reedel õhtul kinos, restoranis, baaris, poes, turul
        - Ma ei käi reedel õhtul kinos, restoranis, baaris, poes, turul


- How to give directions?
    - Positional words
        - ees (in front of), taga (behind), kõrval (next to), sees (inside), väljas (outside), kohal (on top of), all (under), vahel (between)
        - Kirik on muuseumi ees (the object is in omastav case), Olema kooli kõrval
        - When saying to go in somewhere (object in omastv, positional word in kuhu form)
            - Ma lähen muuseumi ette, Ma lähen kiriku taha, Ma lähen poe kõrvale, Ma lähen kooli sisse, Ma lähen turu peale
    - Instructions
        - Mine otse, vasakule, paremale, tagasi
        - Pööra paremale, vasakule
        - Vasakul/paremal pool on pood

    
## Pronouns and Adjectives
- Personal pronouns
    - Mina, sina, tema, meie, teie, nemad/nad
    - Mul, sul, tal, meil, teil, neil + on
        - Mul on vend, sul on sõber, tal on auto, meil on töö, teil on raha, neil on maja
    - Minu, sinu, tema, meie, teie, nende
    - Mulle, sulle, talle, meile, teile, neile
        - Mulle meeldib see raamat, sulle meeldib see muusika, talle meeldib see film, meile meeldib see jook, teile meeldib see toit, neile meeldib see koht

## Tenses
- Present tense
    - Refers to actions happening now or regularly
    - Endings for verbs:
        - Ma + verb + -n
        - Sa + verb + -d
        - Ta + verb + -b
        - Meie + verb + -me
        - Teie + verb + -te
        - Nemad + verb + -vad
    - Da infinitive
        - Use it with Meeldima, oskama, tahtma (to want)
        - Ma tahan mängida jalgpalli, Ma tahan lugeda raamatut, Ma tahan vaadata filmi, Ma tahan kuulata muusikat, Ma tahan süüa õuna, mulle meeldib lugeda raamatut, mul on vaja lugeda raamatut
    - Ma infinite
        - Use it with pidama (to have to), saama (to be able to), hakkama (to manage), minema (to go)
        - Ma hakkan lugema raamatut, Ma pean lugema raamatut, Ma saan lugeda raamatut, Ma lähen lugema raamatut
        - These verbs related to somekind of planning



## To dos: 

- What else to add?
    - Mitu? 
    - Pluural nominatiiv
    - Do you have something on the menu? Mis supp teil on?
    - Dialogue at the market
        - Pluural osastav
    - Kes, kelle oma, kellel on?
    - Positional words + locative
    - Minu pere

# A2 Course Overview

## Minevik (Past Tense)

- Ma olin, sa olid, ta oli, me olime, te olite, nad olid + verb + -nud
    - Ma olin poes, sa olid õues, ta oli taksojuht, me olime pere, te olite pere, nad olid pere, ta ei mänginud jalgpalli, ta ei läinud poodi
- **Täisminevik** (Perfect Tense)
    - Ma olen, sa oled, ta on, me oleme, te olete, nad on + verb + -nud
        - Ma olen sündinud Eestis, sa oled Saaremal käinud, ta oled Tallinnas elanud, me oleme Helsingis käinud, te olete poes käinud, nad on kinno läinud
- **Tingiv Kõnevis** (Mood of Conditional)
    - Ma oleksin, sa oleksid, ta oleks, me oleksime, te oleksite, nad oleksid
        - Ma tahaksin praegu kohvi juua, sa tahaksid kinno minna, ta tahaks restorani minna, me tahaksime reisida, te tahaksite ujuma minna, nad tahaksid jalutama minna
            - Aga lühike vorm on: Ma tahaks kohvi juua, sa tahaks kinno minna, ta tahaks restorani minna, me tahaks reisida, te tahaksite ujuma minna, nad tahaksid jalutama minna
    - Ma, sa, ta, me, te, nad ei tahaks...  
        - Ma ei tahaks praegu kohvi juua, sa ei tahaks kinno minna, ta ei tahaks restorani minna, me ei tahaks reisida, te ei tahaksite ujuma minna, nad ei tahaks jalutama minna
- **Käskiv Kõnevis** (Imperative Mood)
    - (Sina) + verb + -a/-e
        - Tule siia!, Mine ära!, Söö nüüd!, Joo vett!, Loe raamatut!, Kirjuta ülesanne!
    - (Teie) + verb + -ge/-ke
        - Olge hea inimene!, Tulge siia!, Tantsige salsat!, Jooge kiiresti!, Lugege raamatut!, Kirjutage ülesanne!
    - Ära + verb + -a/-e
        - Ära mine ära!, Ära söö seda!, Ära joo seda!, Ära loe seda!, Ära kirjuta seda! 
        - Ära olge inimene!, Ära tulge siia!, Ära tantsige salsat!, Ära jooge kiiresti!, Ära lugege seda!, Ära kirjutage seda!
## Umbisikuline Kõnevis (Passive Voice)
- Verb + -takse
    - See raamat loetakse kiiresti, See maja ehitatakse kiiresti, Minu sünnipäeval laldakse palju kingitusi, Selles poes müüakse head toitu, Selles restoranis süüakse head toitu


## About myself
- Mulle meeldib tennist mängida. Mulle meeldib metsas käimas. Mulle meeldib poes käia. Mulle meeldib tennise mängimine. 
- Mas vorm: verb + -mas
    - Ma olemas poes, talle meeldib poes kaimas

- Kus korter asub?
    - Minu korter asub kesklinnas, minu maja asub äärelinnas, minu suvila asub maal, minu töökoht asub linnas, minu kool asub kesklinnas
- Behind: taga, above: kohal, under: all, next to: kõrval, in front of: ees, between: vahel, oppositve: vastas
    - Minu maja on poe taga, minu korter on kooli kohal, minu töökoht on linna all, minu suvila on metsa kõrval, minu maja on silla ees, minu korter on parkla vahel
    - Minu kodu lähedal on pood, kool, park, apteek, haigla, bussijaam, raudteejaam, lennujaam
- Ma olen sõbralik, ma olen rahulik, ma olen töökas, ma olen rõõmus, ma olen väikne, ma olen ambitioonikas
- Minu hobid on lugemine, matkamine, jooksmine, ujumine, tennise mängimine
- Mul on elukaaslane, mul on üks laps, ta on poiss. Minu elukaaslase nimi on Ann, minu lapse nimi on Alexander. Minu elukaaslase töökoht on linnas, ta on advokaat. 
-  Ma lähen sõbrale külla, ma lähen vanemate juurde külla, ma lähen kolleegide juurde külla
- Ma kain sõbral

